import {renderToStaticMarkup} from 'react-dom/server';
import {expect,it,vi} from 'vitest';
vi.mock('react-native',async()=>await import('react-native-web'));
vi.mock('./design-assets',()=>({Portrait:()=>null,DesignIcon:()=>null}));
vi.mock('./voice-rehearsal',()=>({VoiceRehearsal:()=>null}));
import * as panel from './corrections-panel';
it('provides a dedicated source evening review, immutable before/after and historical chronology views',()=>{expect(panel).toHaveProperty('CorrectionPanel');expect(panel).toHaveProperty('CorrectionReview');expect(panel).toHaveProperty('UnderstandingHistory');expect(renderToStaticMarkup(<panel.UnderstandingHistory items={[]} />)).toContain('Earlier understanding');});
it('does not invent a trainer role when the original evidence has no speaker label',async()=>{const {EvidenceNotes}=await import('./learner-panels');const html=renderToStaticMarkup(<EvidenceNotes items={[{id:'evd_test',sourceConversationId:'70000000-0000-4000-8000-000000000001',sourceRevision:'fictional-r1',startMs:0,endMs:1,quote:'Exact original words.',utteranceIds:['u1']}]} />);expect(html).toContain('Speaker unavailable');expect(html).not.toContain('Trainer');});
it('renders correction target radios with explicit checked and disabled accessibility state',()=>{expect(panel).toHaveProperty('CorrectionTargetOption');const Target=(panel as unknown as {CorrectionTargetOption:React.ComponentType<Record<string,unknown>>}).CorrectionTargetOption,instruction={id:'70000000-0000-4000-8000-000000000001',sourceConversationId:'70000000-0000-4000-8000-000000000002',sourceRevision:'fictional-r1',text:'Exact fictional instruction',situation:'A visitor arrives',expectedAction:'Ask for the code',exceptions:[],sourceEvidence:[],confidence:1,status:'confirmed',createdAt:'2026-09-30T12:00:00.000Z',updatedAt:'2026-09-30T12:00:00.000Z'},props={instruction,source:{utterances:[]},sourceEvidence:[],withheld:false,onSelect:()=>{}};const selected=renderToStaticMarkup(<Target {...props} selected={true} disabled={false}/>),unselected=renderToStaticMarkup(<Target {...props} selected={false} disabled={true}/>);expect(selected).toContain('role="radio"');expect(selected).toContain('aria-checked="true"');expect(selected).toContain('Exact fictional instruction');expect(unselected).toContain('aria-checked="false"');expect(unselected).toContain('aria-disabled="true"');});

it('disables every interpretation meaning control during API or speech work',()=>{const disabled=renderToStaticMarkup(<panel.CorrectionInterpretationOptions meaning='uncertain' disabled={true} onChange={()=>{throw new Error('Busy user edit');}}/>),enabled=renderToStaticMarkup(<panel.CorrectionInterpretationOptions meaning='uncertain' disabled={false} onChange={()=>{}}/>);expect(disabled.match(/aria-disabled="true"/g)).toHaveLength(3);expect(enabled).not.toContain('aria-disabled="true"');expect(disabled).toContain('Original source supports the original instruction');});
