import {expect,it} from 'vitest';
import {createDraftStore} from './draft-store';
const owner='70000000-0000-4000-8000-000000000001',source='70000000-0000-4000-8000-000000000002';
it('stores at most three source-bound correction items with request UUIDs and no original evidence cache',async()=>{const slots:[string|null,string|null]=[null,null];const store=createDraftStore({async read(s){return slots[s];},async write(s,v){slots[s]=v;},async remove(s){slots[s]=null;}});expect(store).toHaveProperty('saveCorrection');const context={kind:'correction' as const,learnerId:owner,sourceConversationId:source,sourceRevision:'r1',instructionRevision:'ir1',slot:0};const metadata={requestId:'70000000-0000-4000-8000-000000000003',after:{type:'transcription' as const,correctedText:'Cannot'},instructionId:'70000000-0000-4000-8000-000000000004',evidenceIds:[`evd_${'a'.repeat(64)}`],status:'pending' as const};await store.saveCorrection(context,'Cannot, not can.','voice',metadata);expect(await store.load(context)).toMatchObject({...metadata,text:'Cannot, not can.'});expect(slots.join('')).not.toContain('sourceEvidence');await expect(store.saveCorrection({...context,slot:3},'Fourth','text',metadata)).rejects.toThrow();await store.clearOwner(owner);expect(await store.load(context)).toBeNull();});
it('does not send a preview or confirm until its exact retry identity is verified on device',async()=>{const helpers=await import('./correction-drafts');expect(helpers).toHaveProperty('submitCorrectionDraft');let calls=0;const store=createDraftStore({async read(){return null;},async write(){throw new Error('Device full');},async remove(){}});await expect(helpers.submitCorrectionDraft({store,context:{kind:'correction',learnerId:owner,sourceConversationId:source,sourceRevision:'r1',instructionRevision:'ir1',slot:0},text:'Remembered wording',inputMode:'text',metadata:{requestId:'70000000-0000-4000-8000-000000000003',after:{type:'transcription',correctedText:'Cannot'},evidenceIds:[],status:'pending'},submit:async()=>{calls++;}})).rejects.toThrow();expect(calls).toBe(0);});
it('retains three pending/skipped correction UUIDs across ordinary draft eviction and dual-slot restart',async()=>{const slots:[string|null,string|null]=[null,null],storage={async read(s:0|1){return slots[s];},async write(s:0|1,v:string){slots[s]=v;},async remove(s:0|1){slots[s]=null;}},store=createDraftStore(storage),contexts=[0,1,2].map(slot=>({kind:'correction' as const,learnerId:owner,sourceConversationId:source,sourceRevision:'r1',instructionRevision:'ir1',slot}));const uuid=(n:number)=>`80000000-0000-4000-8000-${String(n).padStart(12,'0')}`;for(const [index,context] of contexts.entries())await store.saveCorrection(context,`Learner uncertainty ${index}`,'text',{requestId:uuid(index+1),after:{type:'interpretation',meaning:'uncertain'},evidenceIds:[],status:index===1?'skipped':'pending'});for(let index=0;index<30;index++){if(index%2)await store.save({kind:'understanding',learnerId:owner,sourceConversationId:source,sourceRevision:'r1',instructionRevision:'ir1',instructionId:uuid(100+index),phase:'explanation'},'My intended action','text',uuid(200+index));else await store.save({learnerId:owner,sourceConversationId:source,sourceRevision:'r1',instructionRevision:'ir1',practiceSetId:uuid(300+index),scenarioId:uuid(400+index)},'My practice answer','voice');}const restarted=createDraftStore(storage);for(const [index,context] of contexts.entries())expect(await restarted.load(context)).toMatchObject({requestId:uuid(index+1),text:`Learner uncertainty ${index}`});const latest=slots.map(raw=>JSON.parse(raw!).payload).sort((a,b)=>b.generation-a.generation)[0];expect(latest.drafts).toHaveLength(20);expect(latest.drafts.filter((d:{kind?:string})=>d.kind==='correction')).toHaveLength(3);expect(slots.join('')).not.toMatch(/sourceEvidence|utterances|access_token|audio/);await restarted.saveCorrection(contexts[1]!,'','text',{requestId:uuid(2),after:{type:'interpretation',meaning:'uncertain'},evidenceIds:[],status:'skipped'});expect(await createDraftStore(storage).load(contexts[1]!)).toBeNull();});
async function correctionFixture(){const {createSyntheticFirstDayClient,SYNTHETIC_SOURCES}=await import('./synthetic-client'),client=createSyntheticFirstDayClient(),s=SYNTHETIC_SOURCES[0]!,imported=(await client.importConversation({beeSourceId:s.id,sourceKind:'fixture',sourceRevision:s.revision,consent:{confirmed:true}})).sourceConversation,e=await client.extractInstructions({sourceConversationId:imported.id,sourceRevision:s.revision,excludedRanges:[]});for(const i of e.items)await client.updateInstruction({instructionId:i.id,sourceRevision:i.sourceRevision,status:'confirmed'});const i=(await client.getSourceSession(imported.id)).extraction!.items[0]!,p=await client.previewCorrection!({requestId:'70000000-0000-4000-8000-000000000011',target:{sourceConversationId:imported.id,sourceRevision:s.revision,instructionId:i.id,instructionRevision:e.instructionRevision,instruction:i,sourceEvidence:e.sourceEvidence.filter(ev=>i.sourceEvidence.includes(ev.id)),originalUtterances:s.utterances.filter(u=>e.sourceEvidence.filter(ev=>i.sourceEvidence.includes(ev.id)).some(ev=>ev.utteranceIds.includes(u.id)))},after:{type:'interpretation',meaning:'uncertain'},recognizedText:'Historical uncertainty B',inputMode:'text'});return {p,imported,s,e};}
function lifecycleReceipt(p:import('@firstday/contracts').SourceCorrection,request:import('@firstday/contracts').UpdateCorrectionRequest):import('@firstday/contracts').SourceCorrection{return {...p,status:request.action==='confirm'?'confirmed':request.action==='reopen'?'reopened':request.action==='undo'?'undone':'skipped',version:p.version+1,reviewHistory:[...p.reviewHistory,{requestId:request.requestId,action:request.action,request,version:p.version+1,learnerId:p.learnerId,createdAt:p.updatedAt}]};}
it.each(['confirm','reopen','undo'] as const)('history %s reserves its own UUID slot and preserves an unrelated skipped item',async action=>{
  const helpers=await import('./correction-drafts');expect(helpers).toHaveProperty('submitCorrectionLifecycle');
  const {p,imported,s,e}=await correctionFixture();
  const slots:[string|null,string|null]=[null,null],storage={async read(slot:0|1){return slots[slot];},async write(slot:0|1,value:string){slots[slot]=value;},async remove(slot:0|1){slots[slot]=null;}},store=createDraftStore(storage),context={kind:'correction' as const,learnerId:p.learnerId,sourceConversationId:imported.id,sourceRevision:s.revision,instructionRevision:e.instructionRevision,slot:0};await store.saveCorrection(context,'Unresolved A','text',{requestId:'70000000-0000-4000-8000-000000000012',after:{type:'interpretation',meaning:'suggestion'},evidenceIds:[],status:'skipped'});let requestId='';const input={store,context,correction:p,action,id:()=> '70000000-0000-4000-8000-000000000013',async submit(request:import('@firstday/contracts').UpdateCorrectionRequest){requestId=request.requestId;return lifecycleReceipt(p,request);}};const result=await helpers.submitCorrectionLifecycle(input);expect(result.context.slot).toBe(1);expect(requestId).toBe('70000000-0000-4000-8000-000000000013');expect(await createDraftStore(storage).load(context)).toMatchObject({text:'Unresolved A',status:'skipped',requestId:'70000000-0000-4000-8000-000000000012'});if(action!=='reopen')expect(await store.load(result.context)).toBeNull();else expect(await store.load(result.context)).toMatchObject({requestId:p.request.requestId,mutation:{requestId}});
  for(const slot of [1,2])await store.saveCorrection({...context,slot},`Unresolved ${slot}`,'text',{requestId:`70000000-0000-4000-8000-00000000002${slot}`,after:{type:'interpretation',meaning:'uncertain'},evidenceIds:[],status:'pending'});let calls=0;await expect(helpers.submitCorrectionLifecycle({...input,submit:async()=>{calls++;return p;}})).rejects.toThrow();expect(calls).toBe(0);expect(await store.load(context)).toMatchObject({text:'Unresolved A'});
});
it('persists a delayed preview under its captured UUID and refuses to overwrite an intervening different item',async()=>{
  const {submitCorrectionPreview}=await import('./correction-drafts'),{p,imported,s,e}=await correctionFixture(),slots:[string|null,string|null]=[null,null],store=createDraftStore({async read(slot){return slots[slot];},async write(slot,value){slots[slot]=value;},async remove(slot){slots[slot]=null;}}),context={kind:'correction' as const,learnerId:p.learnerId,sourceConversationId:imported.id,sourceRevision:s.revision,instructionRevision:e.instructionRevision,slot:0},request=structuredClone(p.request);let release!:()=>void,started!:()=>void;const wait=new Promise<void>(resolve=>{release=resolve;}),start=new Promise<void>(resolve=>{started=resolve;});let captured='';const pending=submitCorrectionPreview({store,context,request,async submit(r){captured=r.requestId;started();await wait;return p;}});await start;
  request.requestId='70000000-0000-4000-8000-000000000031';request.after={type:'interpretation',meaning:'suggestion'};release();expect(await pending).toEqual(p);expect(captured).toBe(p.request.requestId);expect(await store.load(context)).toMatchObject({requestId:p.request.requestId,after:p.request.after,previewId:p.id,text:p.request.recognizedText});
  const second=submitCorrectionPreview({store,context,request:p.request,async submit(){await new Promise<void>(resolve=>{release=resolve;started();});return p;}});await new Promise<void>(resolve=>setTimeout(resolve,0));await store.saveCorrection(context,'Newer device item','text',{requestId:'70000000-0000-4000-8000-000000000032',after:{type:'interpretation',meaning:'suggestion'},evidenceIds:[],status:'pending'});release();await expect(second).rejects.toThrow();expect(await store.load(context)).toMatchObject({requestId:'70000000-0000-4000-8000-000000000032',text:'Newer device item',after:{meaning:'suggestion'}});
});
it('reuses a history lifecycle UUID after lost response and clears only its own slot on retry',async()=>{
  const {submitCorrectionLifecycle}=await import('./correction-drafts'),{p,imported,s,e}=await correctionFixture(),slots:[string|null,string|null]=[null,null],storage={async read(slot:0|1){return slots[slot];},async write(slot:0|1,value:string){slots[slot]=value;},async remove(slot:0|1){slots[slot]=null;}},context={kind:'correction' as const,learnerId:p.learnerId,sourceConversationId:imported.id,sourceRevision:s.revision,instructionRevision:e.instructionRevision,slot:0};await createDraftStore(storage).saveCorrection(context,'Unresolved A','text',{requestId:'70000000-0000-4000-8000-000000000041',after:{type:'interpretation',meaning:'uncertain'},evidenceIds:[],status:'skipped'});let mutationId='';await expect(submitCorrectionLifecycle({store:createDraftStore(storage),context,correction:p,action:'undo',id:()=> '70000000-0000-4000-8000-000000000042',async submit(r){mutationId=r.requestId;throw new Error('Lost committed response');}})).rejects.toThrow();const pending=(await createDraftStore(storage).loadCorrections(p.learnerId)).find(d=>d.requestId===p.request.requestId)!;expect(pending.slot).toBe(1);expect(pending.mutation!.requestId).toBe(mutationId);await submitCorrectionLifecycle({store:createDraftStore(storage),context,correction:p,action:'undo',id:()=> '70000000-0000-4000-8000-000000000043',async submit(r){expect(r.requestId).toBe(mutationId);return lifecycleReceipt(p,r);}});expect(await createDraftStore(storage).load(context)).toMatchObject({text:'Unresolved A'});expect(await createDraftStore(storage).load({...context,slot:1})).toBeNull();
});
it('explicit revision reuses only the reopened correction slot while identical other targets remain separate',async()=>{
  const {reserveCorrectionReview}=await import('./correction-drafts'),{p,imported,s,e}=await correctionFixture(),slots:[string|null,string|null]=[null,null],store=createDraftStore({async read(slot){return slots[slot];},async write(slot,value){slots[slot]=value;},async remove(slot){slots[slot]=null;}}),context={kind:'correction' as const,learnerId:p.learnerId,sourceConversationId:imported.id,sourceRevision:s.revision,instructionRevision:e.instructionRevision,slot:0};await store.saveCorrection(context,'Unresolved A','text',{requestId:'70000000-0000-4000-8000-000000000051',after:p.request.after,instructionId:p.request.target.instructionId,evidenceIds:p.request.target.instruction.sourceEvidence,status:'skipped'});const b=await reserveCorrectionReview({store,context,correction:p});expect(b.slot).toBe(1);await store.saveCorrection({...context,slot:2},'Unresolved C','text',{requestId:'70000000-0000-4000-8000-000000000052',after:{type:'interpretation',meaning:'suggestion'},instructionId:e.items[1]!.id,evidenceIds:e.items[1]!.sourceEvidence,status:'pending'});const revised=await reserveCorrectionReview({store,context,correction:{...p,status:'reopened'},revisedRequestId:'70000000-0000-4000-8000-000000000053'});expect(revised.slot).toBe(1);expect(revised.revisesId).toBe(p.id);const restored=await reserveCorrectionReview({store,context,correction:{...p,status:'reopened'},revisedRequestId:'70000000-0000-4000-8000-000000000054'});expect(restored.requestId).toBe(revised.requestId);expect(restored.slot).toBe(revised.slot);await expect(store.clearCorrection(context,p.request.requestId)).rejects.toThrow();expect(await store.load(context)).toMatchObject({text:'Unresolved A'});expect(await store.load({...context,slot:2})).toMatchObject({text:'Unresolved C'});
});

it('admits final recognized speech while voice busy but rejects all edits during API work',async()=>{const {correctionEditAllowed}=await import('./correction-drafts');expect(correctionEditAllowed(false,true,'voice')).toBe(true);expect(correctionEditAllowed(false,true,'text')).toBe(false);expect(correctionEditAllowed(true,false,'voice')).toBe(false);expect(correctionEditAllowed(true,true,'text')).toBe(false);expect(correctionEditAllowed(false,false,'text')).toBe(true);});
