import {previewCorrectionRequestSchema,updateCorrectionRequestSchema,sourceCorrectionSchema,type PreviewCorrectionRequest,type UpdateCorrectionRequest,type SourceCorrection} from '@firstday/contracts';
import {createCorrection,updateCorrection,CorrectionStateError,type CorrectionDependencies} from '@firstday/scenario-engine';
import {FirstDayClientError} from './api';
export type CorrectionClient={previewCorrection(request:PreviewCorrectionRequest):Promise<SourceCorrection>;updateCorrection(request:UpdateCorrectionRequest):Promise<SourceCorrection>;listCorrections(sourceConversationId:string):Promise<{items:SourceCorrection[]}>};
export function hasCorrectionClient(client:Partial<CorrectionClient>):client is CorrectionClient{return !!client.previewCorrection&&!!client.updateCorrection&&!!client.listCorrections;}
export function createOfflineCorrectionClient(input:{learnerId:string;validate(request:PreviewCorrectionRequest,historical:boolean):void;validateSource(id:string):void;dependencies(request:PreviewCorrectionRequest,corrections:SourceCorrection[]):CorrectionDependencies;apply(previous:SourceCorrection,next:SourceCorrection):string[]|void;id():string;now():string}):CorrectionClient&{snapshot():SourceCorrection[]}{
  const corrections=new Map<string,SourceCorrection>();
  const conflict=():never=>{throw new FirstDayClientError('REVISION_CONFLICT','Reload this source correction and review its current consequences.');};
  const run=<T,>(op:()=>T):T=>{try{return op();}catch(e){if(e instanceof CorrectionStateError)throw new FirstDayClientError(e.code,'Review the exact source, correction and consequences before continuing.');throw e;}};
  return {
    snapshot(){return [...corrections.values()];},
    async previewCorrection(data){const r=previewCorrectionRequestSchema.parse(data),old=[...corrections.values()].find(c=>c.request.requestId===r.requestId);if(old){input.validate(old.request,true);if(JSON.stringify(r)!==JSON.stringify(old.request))conflict();return sourceCorrectionSchema.parse(old);}if([...corrections.values()].some(c=>c.reviewHistory.some(e=>e.requestId===r.requestId)))conflict();input.validate(r,false);if([...corrections.values()].filter(c=>c.request.target.sourceConversationId===r.target.sourceConversationId).length>=100)conflict();if(r.revisesId){const prior=corrections.get(r.revisesId);if(!prior||prior.status!=='reopened'||JSON.stringify(prior.request.target)!==JSON.stringify(r.target))conflict();}const next=run(()=>createCorrection({id:input.id(),learnerId:input.learnerId,request:r,dependencies:input.dependencies(r,[...corrections.values()]),timestamp:input.now()}));corrections.set(next.id,next);return sourceCorrectionSchema.parse(next);},
    async listCorrections(id){input.validateSource(id);return {items:[...corrections.values()].filter(c=>c.request.target.sourceConversationId===id).map(c=>{input.validate(c.request,true);return sourceCorrectionSchema.parse(c);})};},
    async updateCorrection(data){const r=updateCorrectionRequestSchema.parse(data),old=corrections.get(r.correctionId);if(!old)throw new FirstDayClientError('RESOURCE_NOT_FOUND','Correction unavailable.');input.validate(old.request,true);let next=run(()=>updateCorrection(old,r,input.dependencies(old.request,[...corrections.values()]),input.now()));if(next===old)return sourceCorrectionSchema.parse(old);if([...corrections.values()].some(c=>c.id!==old.id&&c.reviewHistory.some(e=>e.requestId===r.requestId)))conflict();if(r.action==='confirm')input.validate(old.request,false);let previous:SourceCorrection|undefined;if(r.action==='confirm'&&old.request.revisesId){previous=corrections.get(old.request.revisesId);if(!previous||previous.status!=='reopened'||previous.reviewHistory.length>=100)conflict();}const practiceSetIds=input.apply(old,next);if(practiceSetIds?.length)next=sourceCorrectionSchema.parse({...next,reviewHistory:next.reviewHistory.map((e,index)=>index===next.reviewHistory.length-1?{...e,practiceSetIds}:e)});if(previous){const version=previous.version+1;corrections.set(previous.id,sourceCorrectionSchema.parse({...previous,status:'superseded',version,updatedAt:next.updatedAt,reviewHistory:[...previous.reviewHistory,{action:'supersede',requestId:r.requestId,learnerId:input.learnerId,version,createdAt:next.updatedAt}]}));}corrections.set(next.id,next);return sourceCorrectionSchema.parse(next);},
  };
}
