import {recoverCorrectionDraft,submitCorrectionPreview,submitCorrectionLifecycle,reserveCorrectionReview,correctionEditAllowed,CorrectionDraftWriteError} from './correction-drafts';
import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View,Switch} from 'react-native';
import type {SourceConversation,SourceSessionResponse,SourceCorrection,CorrectionAnnotation,UnderstandingBundle,InstructionCard,BeeSource,SourceEvidence} from '@firstday/contracts';
import {correctionWithholds} from '@firstday/scenario-engine';
import type {PracticeClient} from './synthetic-client';
import {hasCorrectionClient} from './corrections-client';
import {hasUnderstandingClient} from './understanding-client';
import {Action,EvidenceNotes,ui} from './learner-panels';
import {VoiceRehearsal} from './voice-rehearsal';
import {useDraftStorage} from './draft-context';
import type {CorrectionDraftContext,CorrectionDraftMetadata} from './draft-store';
import {understandingRequestId} from './understanding-panel';

export function UnderstandingHistory({items}:{items:UnderstandingBundle[]}){return <View style={ui.paper}><Text style={ui.blueLabel}>Earlier understanding</Text><Text style={ui.meta}>Historical record · these earlier actions and contexts cannot be rehearsed here.</Text>{items.map(({check,sourceEvidence})=><View key={check.id} style={ui.divider}><Text style={ui.label}>{check.createdAt} · original intended action</Text><Text style={ui.body}>{check.explanation}</Text><Text style={ui.body}>Original confirmed action: {check.instruction.expectedAction}</Text>{check.instruction.exceptions.map((text,index)=><Text key={index} style={ui.meta}>{text}</Text>)}<EvidenceNotes items={sourceEvidence}/>{check.responses.map(response=><View key={response.requestId}><Text style={ui.body}>{response.responseText}</Text><Text style={ui.meta}>{response.createdAt} · {response.inputMode} · context: {response.applicability.map(v=>v?'applies':'does not apply').join(', ')||'no exceptions'}</Text><Text style={ui.body}>{response.feedback}</Text></View>)}{check.reviewHistory.map((event,index)=><Text key={index} style={ui.meta}>{event.createdAt}: {event.action}</Text>)}</View>)}</View>;}
export function CorrectionReview({correction}:{correction:SourceCorrection}){return <View style={ui.paper}><Text style={ui.blueLabel}>{correction.request.after.type} · {correction.status}</Text><Text style={ui.label}>Exact original source</Text><Text style={ui.meta}>Conversation {correction.request.target.sourceConversationId} · revision {correction.request.target.sourceRevision} · instruction {correction.request.target.instructionId}</Text>{correction.request.target.originalUtterances.map(u=><Text key={u.id} style={ui.meta}>Original speaker: {u.speaker?.name??'name unavailable'} · {u.speaker?.label??'label unavailable'} · utterance {u.id}</Text>)}<EvidenceNotes items={correction.request.target.sourceEvidence}/><Text style={ui.label}>Before meaning</Text><Text style={ui.body}>{correction.beforeMeaning}</Text><Text style={ui.label}>Your reviewed correction</Text><Text style={ui.body}>{correction.request.recognizedText}</Text><Text style={ui.label}>After meaning · separate annotation</Text><Text style={ui.body}>{correction.afterMeaning}</Text><Text style={ui.body}>{correction.effects.consequence}</Text><Text style={ui.meta}>{correction.effects.practiceSetIds.length} affected practice set(s). Original quotes and speakers are retained.</Text>{correction.reviewHistory.map((event,index)=><Text key={index} style={ui.meta}>{event.createdAt}: {event.action} · version {event.version}{event.practiceSetIds?.length?` · fresh current practice: ${event.practiceSetIds.join(', ')}`:''}</Text>)}</View>;}
export function CorrectionTargetOption({instruction:i,source,sourceEvidence,selected,disabled,withheld,onSelect}:{instruction:InstructionCard;source:BeeSource;sourceEvidence:SourceEvidence[];selected:boolean;disabled:boolean;withheld:boolean;onSelect():void}) {
  return <Pressable accessibilityRole='radio' accessibilityLabel={`Correct this exact instruction: ${i.text}. Instruction ${i.id}`} aria-checked={selected} accessibilityState={{checked:selected,disabled}} disabled={disabled} onPress={onSelect} style={ui.paper}><Text style={ui.label}>{selected?'●':'○'} {i.text}</Text><Text style={ui.meta}>{i.id} · {i.status}</Text><Text style={ui.body}>{i.expectedAction}</Text>{source.utterances.filter(u=>sourceEvidence.some(e=>e.utteranceIds.includes(u.id))).map(u=><Text key={u.id} style={ui.meta}>Original speaker: {u.speaker?.name??'name unavailable'} · {u.speaker?.label??'label unavailable'} · utterance {u.id}</Text>)}<EvidenceNotes items={sourceEvidence}/>{withheld&&<Text style={ui.error}>Grading paused by source correction</Text>}</Pressable>;
}
export function CorrectionInterpretationOptions({meaning,disabled,onChange}:{meaning:'suggestion'|'uncertain'|'originalInstruction';disabled:boolean;onChange(value:'suggestion'|'uncertain'|'originalInstruction'):void}){return <>{(['suggestion','uncertain','originalInstruction'] as const).map(value=><Action key={value} secondary disabled={disabled} label={`${meaning===value?'✓ ':''}${value==='originalInstruction'?'Original source supports the original instruction':value==='suggestion'?'Suggestion, not instruction':'Still ambiguous · withhold grading'}`} onPress={()=>{if(!disabled)onChange(value);}}/>)}</>;}
const labels:{type:CorrectionAnnotation['type'];label:string}[]=[{type:'attribution',label:'Who said it'},{type:'transcription',label:'Words were wrong'},{type:'interpretation',label:'Meaning was wrong'},{type:'newRule',label:'Actual later rule'}];
const initialAfter:CorrectionAnnotation={type:'interpretation',meaning:'uncertain'};
export function CorrectionPanel({client,source,isVisible,onExit}:{client:PracticeClient;source:SourceConversation;isVisible:boolean;onExit():void}){
  const draftStorage=useDraftStorage();
  const [session,setSession]=useState<SourceSessionResponse|null>(null),[sources,setSources]=useState<SourceConversation[]>([]),[items,setItems]=useState<SourceCorrection[]>([]),[history,setHistory]=useState<UnderstandingBundle[]>([]),[slot,setSlot]=useState(0),[selectedSource,setSelectedSource]=useState(source),[text,setText]=useState(''),[mode,setMode]=useState<'voice'|'text'>('text'),[after,setAfter]=useState<CorrectionAnnotation>(initialAfter),[instructionId,setInstructionId]=useState<string|null>(null),[preview,setPreview]=useState<SourceCorrection|null>(null),[reviewed,setReviewed]=useState(false),[evidenceReviewed,setEvidenceReviewed]=useState(false),[laterId,setLaterId]=useState<string|null>(null),[busy,setBusy]=useState(false),[voiceBusy,setVoiceBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[revisesId,setRevisesId]=useState<string|undefined>();
  const lock=useRef(false),alive=useRef(true),requestId=useRef(understandingRequestId()),pendingMutation=useRef<CorrectionDraftMetadata['mutation']>(undefined);
  const [reloadSequence,setReloadSequence]=useState(0),[sourceCursor,setSourceCursor]=useState<string|null>(null);
  const context:CorrectionDraftContext={kind:'correction',learnerId:source.learnerId,sourceConversationId:selectedSource.id,sourceRevision:selectedSource.sourceRevision,instructionRevision:session?.extraction?.instructionRevision??'pending',slot};
  const revisesCorrection=items.find(c=>c.id===revisesId),revisesCanonical=revisesCorrection?.request.after.type==='newRule';
  const instruction=revisesCanonical?revisesCorrection.request.target.instruction:session?.extraction?.items.find(i=>i.id===instructionId);
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  useEffect(()=>{let cancelled=false;setLoaded(false);setError(null);setSession(null);if(!hasCorrectionClient(client))return;void (async()=>{
    const current=await client.getSourceSession(selectedSource.id);if(current.sourceConversation.learnerId!==source.learnerId)throw new Error('Wrong source owner');const corrections=await client.listCorrections(selectedSource.id),past=hasUnderstandingClient(client)?await client.listUnderstanding(selectedSource.id,true):{items:[]};const recovered=current.extraction?await recoverCorrectionDraft({store:draftStorage,context:{...context,instructionRevision:current.extraction.instructionRevision},session:current,corrections:corrections.items}):null;const saved=recovered?.draft;
    if(cancelled)return;setSession(current);setItems(corrections.items);setHistory(past.items);setPreview(null);setText('');setMode('text');setAfter(initialAfter);setInstructionId(null);setReviewed(false);setEvidenceReviewed(false);setRevisesId(undefined);requestId.current=understandingRequestId();pendingMutation.current=undefined;
    if(saved&&'kind' in saved&&saved.kind==='correction'){
      if(saved.instructionId&&!current.extraction?.items.some(i=>i.id===saved.instructionId&&i.sourceEvidence.length===saved.evidenceIds.length&&i.sourceEvidence.every((id,index)=>id===saved.evidenceIds[index])))throw new Error('Saved target changed');
      setText(saved.text);setMode(saved.inputMode);setAfter(saved.after);setInstructionId(saved.instructionId??null);setRevisesId(saved.revisesId);requestId.current=saved.requestId;pendingMutation.current=saved.mutation;
      const receipt=recovered?.receipt;if(receipt){setPreview(receipt);setReviewed(true);setEvidenceReviewed(true);if(recovered?.mutationCommitted){pendingMutation.current=undefined;setNotice('The saved correction receipt was restored without repeating confirmation.');}else setNotice('Your pending correction and retry identity were restored. Review before continuing.');}else setNotice(saved.status==='skipped'?'Skipped uncertainty restored. You can leave it unresolved.':'Your unsubmitted correction was restored.');
    }
    setLoaded(true);
  })().catch(()=>{if(!cancelled){setError('This source or its saved review is unavailable. Reopen consented training before restoring a correction.');}});return()=>{cancelled=true;};},[client,selectedSource.id,slot,reloadSequence]);
  useEffect(()=>{let cancelled=false;void client.listSavedSources({sourceKind:source.sourceKind,limit:20}).then(page=>{if(!cancelled){setSources(page.items);setSourceCursor(page.nextCursor);}}).catch(()=>{});return()=>{cancelled=true;};},[client,source.sourceKind]);
  async function run(operation:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError(null);try{await operation();}catch(error){if(alive.current)setError(error instanceof CorrectionDraftWriteError?'Your correction and retry identity could not be saved on this device, so no request was sent. Clear an existing item or retry.':'This review could not finish. Your saved work is retained. Reload the source; a changed preview must be reviewed again.');}finally{lock.current=false;if(alive.current)setBusy(false);}}
  async function persist(metadata?:Partial<CorrectionDraftMetadata>,value=text,inputMode=mode){if(!session?.extraction)throw new Error('Select extracted source');const m:CorrectionDraftMetadata={requestId:requestId.current,after,instructionId:instructionId??undefined,evidenceIds:instruction?.sourceEvidence??[],status:'pending',...(preview?{previewId:preview.id}:{}),...(revisesId?{revisesId}:{}),...(pendingMutation.current?{mutation:pendingMutation.current}:{}),...metadata};await draftStorage.saveCorrection(context,value,inputMode,m);}
  function edit(value:string,inputMode:'text'|'voice'){if(!correctionEditAllowed(lock.current,voiceBusy,inputMode))return;setText(value);setMode(inputMode);setReviewed(false);setPreview(null);requestId.current=understandingRequestId();pendingMutation.current=undefined;void persist({requestId:requestId.current},value,inputMode).catch(()=>setNotice('The device draft could not be saved. Saving is required before sending.'));}
  function changeAfter(value:CorrectionAnnotation,fromComparison=false){if((lock.current&&!fromComparison)||voiceBusy)return;setAfter(value);setPreview(null);setReviewed(false);requestId.current=understandingRequestId();pendingMutation.current=undefined;void persist({after:value,requestId:requestId.current}).catch(()=>{});}
  async function makePreview(){if(!hasCorrectionClient(client)||!instruction||!session?.extraction||!reviewed||!evidenceReviewed)return;
    const request={requestId:requestId.current,target:revisesCanonical?revisesCorrection.request.target:{sourceConversationId:selectedSource.id,sourceRevision:selectedSource.sourceRevision,instructionId:instruction.id,instructionRevision:session.extraction.instructionRevision,instruction,originalUtterances:session.source.utterances.filter(u=>session.extraction!.sourceEvidence.filter(e=>instruction.sourceEvidence.includes(e.id)).some(e=>e.utteranceIds.includes(u.id))),sourceEvidence:instruction.sourceEvidence.map(id=>session.extraction!.sourceEvidence.find(e=>e.id===id)!)},after,recognizedText:text.trim(),inputMode:mode,...(revisesId?{revisesId}:{})};
    const p=await submitCorrectionPreview({store:draftStorage,context,request,submit:r=>client.previewCorrection!(r)});setPreview(p);setItems(v=>[...v.filter(c=>c.id!==p.id),p]);
  }
  async function loadReview(c:SourceCorrection,revise=false){
    const draft=await reserveCorrectionReview({store:draftStorage,context,correction:c,...(revise?{revisedRequestId:understandingRequestId()}:{})});setSlot(draft.slot);setReloadSequence(v=>v+1);
  }
  async function act(c:SourceCorrection,action:'confirm'|'skip'|'reopen'|'undo'){
    if(!hasCorrectionClient(client))return;const selected=requestId.current===c.request.requestId;
    const {receipt:result,context:reviewContext}=await submitCorrectionLifecycle({store:draftStorage,context,correction:c,action,id:understandingRequestId,submit:r=>client.updateCorrection!(r)});
    if(selected){pendingMutation.current=undefined;setPreview(result);}setItems((await client.listCorrections(selectedSource.id)).items);setSession(await client.getSourceSession(selectedSource.id));setNotice(action==='undo'?'Annotation undone. Historical practice stays historical; current confirmed rules can prepare a fresh set.':`Review saved in item ${reviewContext.slot+1}. Original source records and other device items are retained.`);
  }
  if(!hasCorrectionClient(client))return <View style={ui.paper}><Text style={ui.body}>Source correction needs the current FirstDay connection.</Text><Action label='Back to training' onPress={onExit}/></View>;
  const blocked=items.filter(correctionWithholds);
  return <View style={ui.section}><Text style={ui.title}>Evening source review</Text><Text style={ui.body}>Review up to three important uncertainties. Leave unresolved items skipped. Choose the exact conversation and source moment yourself.</Text><View style={ui.row}>{[0,1,2].map(index=><Action key={index} secondary label={`Item ${index+1}${slot===index?' · selected':''}`} disabled={busy||voiceBusy} onPress={()=>{if(!lock.current&&!voiceBusy)setSlot(index);}}/>)}</View>
    <Text style={ui.label}>Selected consented conversation</Text>{sources.map(s=><Action key={s.id} secondary label={`${s.title} · ${s.startedAt} · ${s.id===selectedSource.id?'selected':s.id}`} disabled={busy||voiceBusy||revisesCanonical} onPress={()=>{if(!lock.current&&!voiceBusy)setSelectedSource(s);}}/>)}{sourceCursor&&<Action secondary disabled={busy||voiceBusy} label='More consented conversations' onPress={()=>void run(async()=>{const page=await client.listSavedSources({sourceKind:source.sourceKind,cursor:sourceCursor,limit:20});setSources(current=>[...current,...page.items.filter(s=>!current.some(c=>c.id===s.id))]);setSourceCursor(page.nextCursor);})}/>}
    {loaded&&session&&<><Text style={ui.meta}>Source {selectedSource.id} · revision {selectedSource.sourceRevision}</Text><Text style={ui.label}>Your correction · review recognized words</Text><VoiceRehearsal active={isVisible&&!busy&&loaded} prompt='What did you notice was wrong? Review the recognized words, then choose the exact original source.' onBusy={setVoiceBusy} onTranscript={value=>edit(value,'voice')}/><TextInput editable={!busy&&!voiceBusy} accessibilityLabel='Correction recognized text' multiline maxLength={4000} style={ui.input} value={text} onChangeText={value=>edit(value,'text')}/><View style={ui.permissionRow}><Text style={[ui.body,ui.permissionText]}>I reviewed these recognized words</Text><Switch style={ui.permissionSwitch} accessibilityLabel='I reviewed the recognized correction text' disabled={busy||voiceBusy} value={reviewed} onValueChange={value=>{if(!lock.current&&!voiceBusy)setReviewed(value);}}/></View>
    <Text style={ui.label}>Choose one exact original instruction and its source spans</Text>{session.extraction?.items.map(i=><CorrectionTargetOption key={i.id} instruction={i} source={session.source} sourceEvidence={session.extraction!.sourceEvidence.filter(e=>i.sourceEvidence.includes(e.id))} selected={instructionId===i.id} disabled={i.status!=='confirmed'||busy||voiceBusy||revisesCanonical} withheld={blocked.some(c=>c.effects.instructionIds.includes(i.id))} onSelect={()=>{if(lock.current||voiceBusy)return;setInstructionId(i.id);setEvidenceReviewed(false);setPreview(null);requestId.current=understandingRequestId();void persist({instructionId:i.id,evidenceIds:i.sourceEvidence,requestId:requestId.current}).catch(()=>setNotice("Target selection could not be saved on this device."));}}/>)}
    {instruction&&<View style={ui.permissionRow}><Text style={[ui.body,ui.permissionText]}>These exact quotes, original speakers and ordered source moments are my target. The annotation applies only to these selected spans, including every speaker shown in a mixed span.</Text><Switch style={ui.permissionSwitch} accessibilityLabel='Confirm exact original evidence target' value={evidenceReviewed} disabled={busy||voiceBusy} onValueChange={value=>{if(!lock.current&&!voiceBusy)setEvidenceReviewed(value);}}/></View>}
    <Text style={ui.label}>Correction type</Text>{labels.map(item=><Action key={item.type} secondary disabled={busy||voiceBusy||revisesCanonical&&item.type!=='newRule'} label={`${after.type===item.type?'✓ ':''}${item.label}`} onPress={()=>changeAfter(item.type==='attribution'?{type:'attribution',speakerName:'',speakerRole:'',preparation:'withhold'}:item.type==='transcription'?{type:'transcription',correctedText:text}:item.type==='interpretation'?initialAfter:{type:'newRule',changeId:'',laterSourceConversationId:'',laterSourceRevision:''})}/>)}
    {after.type==='attribution'&&<><TextInput editable={!busy&&!voiceBusy} accessibilityLabel='Corrected speaker name for this conversation' placeholder='Speaker name, for this conversation only' style={ui.input} value={after.speakerName} onChangeText={speakerName=>changeAfter({...after,speakerName})}/><TextInput editable={!busy&&!voiceBusy} accessibilityLabel='Corrected speaker role' placeholder='Speaker role' style={ui.input} value={after.speakerRole} onChangeText={speakerRole=>changeAfter({...after,speakerRole})}/><Action secondary disabled={busy||voiceBusy} label={after.preparation==='withhold'?'✓ Withhold inappropriate preparation':'Withhold inappropriate preparation'} onPress={()=>changeAfter({...after,preparation:'withhold'})}/><Action secondary disabled={busy||voiceBusy} label={after.preparation==='retain'?'✓ Keep source-supported preparation':'Keep source-supported preparation'} onPress={()=>changeAfter({...after,preparation:'retain'})}/><Text style={ui.meta}>This labels only this conversation. Original speaker and quote remain intact.</Text></>}
    {after.type==='transcription'&&<><TextInput editable={!busy&&!voiceBusy} accessibilityLabel='User-corrected wording' multiline maxLength={4000} placeholder='Exact wording you remember' style={ui.input} value={after.correctedText} onChangeText={correctedText=>changeAfter({...after,correctedText})}/><Text style={ui.meta}>Your remembered wording stays separate from the original transcript. Disputed policy stays ungraded.</Text></>}
    {after.type==='interpretation'&&<CorrectionInterpretationOptions meaning={after.meaning} disabled={busy||voiceBusy} onChange={meaning=>changeAfter({...after,meaning})}/>}
    {revisesCanonical&&<Text style={ui.meta}>Revise your reviewed words for this same confirmed canonical change. The original target and actual later source stay fixed; clear this device item to start another uncertainty.</Text>}{after.type==='newRule'&&!revisesCanonical&&<><Text style={ui.body}>Select an actual later source that you already imported and allowed. Its comparison must supply a canonical changed rule.</Text>{sources.filter(s=>s.startedAt>selectedSource.startedAt).map(s=><Action secondary disabled={busy||voiceBusy} key={s.id} label={`${s.title} · ${s.startedAt} · ${s.id}${laterId===s.id?' · selected':''}`} onPress={()=>{if(!lock.current&&!voiceBusy)setLaterId(s.id);}}/>)}<Action secondary label='Compare selected actual later source' disabled={busy||voiceBusy||!laterId||!session.extraction} onPress={()=>void run(async()=>{const next=await client.getSourceSession(laterId!);if(!next.extraction)throw new Error('Extract actual update first');const result=await client.compareSources({sourceConversationId:selectedSource.id,newSourceConversationId:next.sourceConversation.id,previousInstructionRevision:session.extraction!.instructionRevision});const candidates=result.changes.filter(c=>c.previousInstructionId===instructionId);if(candidates.length!==1)throw new Error('Choose an exact changed instruction');const change=candidates[0]!;changeAfter({type:'newRule',changeId:change.id,laterSourceConversationId:next.sourceConversation.id,laterSourceRevision:next.sourceConversation.sourceRevision},true);})}/>{after.changeId&&<Text style={ui.meta}>Selected canonical change: {after.changeId}</Text>}</>}
    <Action label='Preview correction and consequences' disabled={busy||voiceBusy||!text.trim()||!reviewed||!instruction||(!revisesCanonical&&instruction.status!=='confirmed')||!evidenceReviewed} onPress={()=>void run(makePreview)}/><Action secondary disabled={busy||voiceBusy} label='Clear this device item' onPress={()=>void run(async()=>{await draftStorage.saveCorrection(context,'','text',{requestId:understandingRequestId(),after:initialAfter,evidenceIds:[],status:'pending'});setReloadSequence(v=>v+1);})}/><Action secondary label='Skip this unresolved item' disabled={busy||voiceBusy||!text.trim()} onPress={()=>void run(async()=>{if(preview&&['preview','skipped','reopened'].includes(preview.status))await act(preview,'skip');else {await persist({status:'skipped'});setNotice('Skipped item saved for later. No correction was applied.');}})}/>
    {preview&&<><CorrectionReview correction={preview}/>{['preview','skipped'].includes(preview.status)&&<Action label='Confirm this exact correction' disabled={busy||voiceBusy} onPress={()=>void run(()=>act(preview,'confirm'))}/>}</>}
    </>}
    <Text style={ui.label}>Saved source correction chronology</Text>{items.filter(c=>c.id!==preview?.id).map(c=><View key={c.id}><CorrectionReview correction={c}/>{['preview','skipped'].includes(c.status)&&<Action secondary disabled={busy||voiceBusy} label='Review this pending item' onPress={()=>void run(()=>loadReview(c))}/>}{c.status==='confirmed'&&<Action secondary disabled={busy||voiceBusy} label='Reopen correction review' onPress={()=>void run(()=>act(c,'reopen'))}/>}{['confirmed','reopened'].includes(c.status)&&<Action secondary disabled={busy||voiceBusy} label='Undo local annotation after source review' onPress={()=>void run(()=>act(c,'undo'))}/>}{c.status==='reopened'&&<Action secondary disabled={busy||voiceBusy} label='Revise reopened annotation' onPress={()=>void run(()=>loadReview(c,true))}/>}</View>)}
    {preview?.status==='confirmed'&&<Action secondary disabled={busy||voiceBusy} label='Reopen this correction review' onPress={()=>void run(()=>act(preview,'reopen'))}/>}{preview&&['confirmed','reopened'].includes(preview.status)&&<Action secondary disabled={busy||voiceBusy} label='Undo this local annotation after source review' onPress={()=>void run(()=>act(preview,'undo'))}/>}{preview?.status==='reopened'&&<Action secondary disabled={busy||voiceBusy} label='Revise this reopened annotation' onPress={()=>void run(()=>loadReview(preview,true))}/>}
    <UnderstandingHistory items={history}/>{notice&&<Text style={ui.meta}>{notice}</Text>}{error&&<Text accessibilityRole='alert' style={ui.error}>{error}</Text>}<Action secondary disabled={busy||voiceBusy} label='Reload source and saved review' onPress={()=>{setReloadSequence(v=>v+1);}}/><Action disabled={busy||voiceBusy} label='Back to training' onPress={onExit}/>
  </View>;
}
