import { renderToStaticMarkup } from "react-dom/server";
import { describe,expect,it,vi } from "vitest";
import { createUnderstandingCheck } from "@firstday/scenario-engine";
import { instructionCardSchema } from "@firstday/contracts";
vi.mock("react-native",async()=>await import("react-native-web"));
vi.mock("./design-assets",()=>({Portrait:()=>null,DesignIcon:()=>null}));
vi.mock("./voice-rehearsal",()=>({VoiceRehearsal:()=>null}));
import { UnderstandingComparison } from "./understanding-panel";
const time="2026-09-30T12:00:00.000Z";
const rule=instructionCardSchema.parse({id:"11111111-1111-4111-8111-111111111111",sourceConversationId:"22222222-2222-4222-8222-222222222222",sourceRevision:"r1",text:"Reservation window",situation:"A four-day reservation",expectedAction:"New reservations last three days.",exceptions:["Reservations already made keep their original seven-day window."],status:"confirmed",confidence:1,sourceEvidence:[`evd_${"a".repeat(64)}`],createdAt:time,updatedAt:time});
const check=createUnderstandingCheck({id:"33333333-3333-4333-8333-333333333333",requestId:"44444444-4444-4444-8444-444444444444",instruction:rule,instructionRevision:"ir1",explanation:"I would cancel this four-day reservation.",inputMode:"voice",timestamp:time});
describe("understanding comparison screen",()=>{
 it("shows learner intent beside the exact conditional distinction and asks temporal context before a judgment",()=>{const markup=renderToStaticMarkup(<UnderstandingComparison check={check} evidence={[]} busy={false} onContext={()=>{}} onConfirm={()=>{}} onDispute={()=>{}} onReopen={()=>{}} />);expect(markup).toContain("I would cancel this four-day reservation.");expect(markup).toContain("New reservations last three days.");expect(markup).toContain("original seven-day window");expect(markup).toContain("Was this reservation made before the policy change?");expect(markup).toContain("I don’t know yet");expect(markup).not.toContain("Your answer is wrong");});
 it("never substitutes demo numbers for a different confirmed policy",()=>{const changed={...check,instruction:{...check.instruction,expectedAction:"New reservations last two days.",exceptions:["Reservations already made keep their original nine-day window."]}};const markup=renderToStaticMarkup(<UnderstandingComparison check={changed} evidence={[]} busy={false} onContext={()=>{}} onConfirm={()=>{}} onDispute={()=>{}} onReopen={()=>{}}/>);expect(markup).toContain("two days");expect(markup).toContain("nine-day");expect(markup).not.toContain("three days");expect(markup).not.toContain("seven-day");});
 it("does not give temporal mismatch wording to an unrelated selected exception",()=>{const changed={...check,instruction:{...check.instruction,exceptions:[...check.instruction.exceptions,"A manager may provide a lost collection code."]},initialComparison:{answerQuote:check.explanation,exceptionIndex:1},applicability:[null,null]};const markup=renderToStaticMarkup(<UnderstandingComparison check={changed} evidence={[]} busy={false} onContext={()=>{}} onConfirm={()=>{}} onDispute={()=>{}} onReopen={()=>{}}/>);expect(markup).not.toContain("may need to change depending on whether the reservation was already made");expect(markup).toContain("Check each condition");});
 it("offers actionable source review/reopening while withholding rehearsal for disputes",()=>{const markup=renderToStaticMarkup(<UnderstandingComparison check={{...check,status:"disputed"}} evidence={[]} busy={false} onContext={()=>{}} onConfirm={()=>{}} onDispute={()=>{}} onReopen={()=>{}} />);expect(markup).toContain("Reopen after reviewing the source");expect(markup).toContain("Grading this instruction is paused");expect(markup).not.toContain("Use this context for rehearsal");});
});
