import { describe,expect,it } from "vitest";
import { createDraftStore, type UnderstandingDraftContext } from "./draft-store";
import { recoverUnderstandingDraft,submitUnderstandingDraft } from "./understanding-drafts";
const context:UnderstandingDraftContext={kind:"understanding",learnerId:"11111111-1111-4111-8111-111111111111",sourceConversationId:"22222222-2222-4222-8222-222222222222",instructionId:"33333333-3333-4333-8333-333333333333",sourceRevision:"r1",instructionRevision:"ir1",phase:"rehearsal",checkId:"44444444-4444-4444-8444-444444444444"};
const requestId="55555555-5555-4555-8555-555555555555",newId="66666666-6666-4666-8666-666666666666";
function storage(){const values=new Map<number,string>();return {values,slots:{async read(slot:0|1){return values.get(slot)??null;},async write(slot:0|1,value:string){values.set(slot,value);},async remove(slot:0|1){values.delete(slot);}}};}
describe("understanding submission identity recovery",()=>{
 it("retains the retry UUID with a voice draft across store/remount restart",async()=>{const {slots}=storage();const store=createDraftStore(slots);await store.save(context,"Keep it","voice",requestId);const restored=await recoverUnderstandingDraft({context,bundles:[],store:createDraftStore(slots),id:()=>newId});expect(restored.requestId).toBe(requestId);expect(restored.draft?.text).toBe("Keep it");expect(restored.draft?.inputMode).toBe("voice");});
 it("persists the UUID before network and prevents submission if durable saving fails",async()=>{const {slots}=storage();let calls=0;await expect(submitUnderstandingDraft({context,text:"Keep it",inputMode:"text",requestId,store:createDraftStore({...slots,async write(){throw new Error("Full");}}),async submit(){calls++;}})).rejects.toThrow("retry identity");expect(calls).toBe(0);});
 it("upgrades a legacy draft without UUID before its first submission and preserves exact context isolation",async()=>{const {slots}=storage(),store=createDraftStore(slots);await store.save(context,"Legacy text","text");const restored=await recoverUnderstandingDraft({context,bundles:[],store:createDraftStore(slots),id:()=>newId});expect(restored.requestId).toBe(newId);await submitUnderstandingDraft({context,text:restored.draft!.text,inputMode:"text",requestId:restored.requestId,store,async submit(){expect((await store.load(context))).toMatchObject({requestId:newId});}});expect(await store.load({...context,learnerId:newId})).toBeNull();expect(await store.load({...context,instructionRevision:"ir2"})).toBeNull();});
});
